### ISSUE TITLE
There are still two `登入` within the doc

### ISSUE THREAD

**Issue by doggy8088** [dotnet/AspNetCore.Docs.zh-tw#138]
Related to https://github.com/aspnet/AspNetCore.Docs.zh-tw/issues/127

There are still two `登入` within the doc. Please modify it completely.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [.NET Core 與 ASP.NET Core 中的記錄](https://docs.microsoft.com/zh-tw/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @doggy8088,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team

**Comment by doggy8088** [comment]
@srvbpigh There are still 1 `登入` in the doc.

![image](https://user-images.githubusercontent.com/88981/71995831-7d9b2400-323b-11ea-967c-c56b94b36c57.png)

**Comment by CeciAc** [comment]
Hello, @doggy8088 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#create-logs-in-the-program-class

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by doggy8088** [comment]
@CeciAc What's the problem of this translation process? 

The title become wrong translation again!

![image](https://user-images.githubusercontent.com/88981/72302969-a6da0b00-36a6-11ea-8aab-b496396089d8.png)

The one I mentioned is not fixed yet, but you still closed the issue.

![image](https://user-images.githubusercontent.com/88981/72303001-bc4f3500-36a6-11ea-9b0a-daee6174c094.png)

I'm really disappointed now.

**Comment by CeciAc** [comment]
Hi @doggy8088 
Thanks for flagging this issue. We are investigating what is causing the fixes to revert.

Will keep this issue open until it's fixed

Kind regards,
Microsoft DOCS International Team
